name: Deploy Environment

inputs:
  environment:
    required: true
    type: string
  azureSubscription:
    required: true
  azureClientId:
    required: true
  azureTenantId:
    required: true

permissions:
  id-token: write
  contents: read

runs:
  using: 'composite'
  steps:
    - id: UpperEnvironment
      uses: ASzc/change-string-case-action@v6
      with:
        string: ${{ inputs.environment }}

    - name: Create Resource Group (if not exists)
      uses: azure/cli@v1
      with:
        inlineScript: |
          az group create \
            --name IS-Licensing-${{ steps.UpperEnvironment.outputs.capitalized }} \
            --location centralus

    - name: Run ARM Template Deployment
      id: arm_deployment
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ inputs.azureSubscription }}
        resourceGroupName: IS-Licensing-${{ steps.UpperEnvironment.outputs.capitalized }}
        template: ./deployment/is-licensing.template.json
        parameters: ./deployment/environments/is-licensing.${{ inputs.environment }}.json

    - name: Deploy Azure Function App
      uses: Azure/functions-action@v1
      with:
        app-name: is-licensing-${{ inputs.environment }}-svc
        package: ./downloaded-artifact
