name: Pull Request Build

on:
  pull_request:
    branches:
      - main
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.sln'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'  # Change to your version

      - name: Restore dependencies
        working-directory: ./src
        run: dotnet restore

      - name: Build
        working-directory: ./src
        run: dotnet build --no-restore --configuration Release
